AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kms-client

  Sample SAM Template for kms-client
  
Globals:
  Function:
    Timeout: 3

Resources:
  KMSClientFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Name: kms-client
    Properties:
      Handler: src/app.lambdaHandler
      Runtime: nodejs14.x
      Role: arn:aws:iam::xxxx:role/simple-lambda-execution-role

Outputs:
  KMSClientFunction:
    Description: "KMS Client Lambda Function ARN"
    Value: !GetAtt KMSClientFunction.Arn
